name: naver_map_weather
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  http: ^0.13.3
  cupertino_icons: ^1.0.6
  flutter_naver_map: ^1.2.2+flutter3.22


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
